steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/predictive-maintenance-448107/mlops/predictive-maintenance:$COMMIT_SHA'
      - '-t'
      - 'asia-east1-docker.pkg.dev/predictive-maintenance-448107/mlops/predictive-maintenance:latest'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/predictive-maintenance-448107/mlops/predictive-maintenance:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/predictive-maintenance-448107/mlops/predictive-maintenance:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'predictive-maintenance-service'
      - '--image'
      - 'asia-east1-docker.pkg.dev/predictive-maintenance-448107/mlops/predictive-maintenance:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'

substitutions:
  _REGION: asia-east1
  _PROJECT_ID: predictive-maintenance-448107
  _REPOSITORY_NAME: mlops
