options:
  logging: CLOUD_LOGGING_ONLY  # Fixes Cloud Build logging issue

steps:
  # Build and Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'  # Ensures compatibility with Cloud Run
      - '--push'  # Pushes image to registry after build
      - '-t'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:$COMMIT_SHA'
      - '-t'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:latest'
      - '-f'
      - 'Dockerfile.fastapi.txt'  # Your Dockerfile name
      - '.'  # Context directory

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-app-service'  # Cloud Run service name
      - '--image'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'
      - '--quiet'  # Suppress logs for automation

substitutions:
  _REGION: asia-east1
  _PROJECT_ID: rugged-baton-448820-a2
