options:
  logging: CLOUD_LOGGING_ONLY  # Fixes the Cloud Build logging issue

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:$COMMIT_SHA'
      - '-t'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:latest'
      - '-f'  # Specify the Dockerfile to use
      - 'Dockerfile.fastapi.txt'  # Your custom Dockerfile name
      - '.'  # Context directory

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-app-service'  # Name of the Cloud Run service
      - '--image'
      - 'asia-east1-docker.pkg.dev/rugged-baton-448820-a2/mlops/fastapi-app:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'

substitutions:
  _REGION: asia-east1
  _PROJECT_ID: rugged-baton-448820-a2
  _REPOSITORY_NAME: mlops
