steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:$COMMIT_SHA'
      - '-t'
      - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:latest'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'predictive-maintenance-service'
      - '--image'
      - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'

substitutions:
  _REGION: asia-east1
  _PROJECT_ID: mlops-test-443704
  _REPOSITORY_NAME: mlops

options:
  logging: NONE
  substitution_option: ALLOW_LOOSE
