steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:latest'
      - '.'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:latest'

  # Step 3: Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--image-url=asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:latest'
      - '--quiet'

images:
  - 'asia-east1-docker.pkg.dev/mlops-test-443704/mlops/predictive-maintenance:latest'

substitutions:
  _REGION: 'asia-east1'
  _SERVICE: 'default'

timeout: '900s'  # Extend timeout for deployments
